{{- range $name, $spec := .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metagrid.fullname" $ }}-{{ regexReplaceAll "\\W+" $name "-" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson (dict "auths" (dict $name $spec) ) | b64enc | quote }}
{{- end }}
